/**
 * What's New LLM Synthesis
 *
 * Two-pass LLM synthesis with static fallback for reliable report generation.
 * - Pass 1: Generate initial synthesis from findings
 * - Pass 2: Refine and improve the synthesis
 * - Static Fallback: Template-based report when LLM unavailable
 */

"use node";

import { generateText } from "ai";
import { zaiPro, zaiFlash } from "../lib/ai/zai_provider";

// ============================================================================
// Types
// ============================================================================

interface Finding {
  title: string;
  url: string;
  source: string;
  category: "discovery" | "release" | "trend" | "discussion";
  score?: number;
  summary?: string;
  publishedAt?: string;
  engagementVelocity?: number;
  crossSourceCorroboration?: number;
  author?: string;
  tags?: string[];
  metadataJson?: any;
}

interface ToolSuggestion {
  id: string;
  title: string;
  description: string;
  category: "libraries" | "cli" | "framework" | "service" | "database" | "tool";
  sourceUrl: string;
  sourceType: "github" | "npm" | "pypi" | "website" | "cargo" | "go" | "other";
  language?: string;
  tags: string[];
  useCases: string[];
}

interface SynthesisResult {
  markdown: string;
  method: "llm-two-pass" | "static-fallback";
  pass1Content?: string;
  error?: string;
  toolSuggestions?: ToolSuggestion[];
}

// ============================================================================
// Pass 1: Initial Synthesis
// ============================================================================

/**
 * Generate initial synthesis from raw findings
 *
 * This pass:
 * - Groups findings by category
 * - Identifies top stories by engagement
 * - Creates structured report outline
 * - Extracts key themes and connections
 */
async function generateInitialSynthesis(
  findings: Finding[],
  days: number,
  periodStart: Date,
  periodEnd: Date
): Promise<string> {
  const formatDate = (d: Date) => d.toISOString().split("T")[0];

  // Categorize findings for the prompt
  const discoveries = findings.filter((f) => f.category === "discovery");
  const releases = findings.filter((f) => f.category === "release");
  const discussions = findings.filter((f) => f.category === "discussion");
  const trends = findings.filter((f) => f.category === "trend");

  // Build top findings by score/engagement
  const topFindings = [...findings]
    .sort((a, b) => (b.score ?? 0) - (a.score ?? 0))
    .slice(0, 20);

  const findingsJson = JSON.stringify(
    topFindings.map((f) => ({
      title: f.title,
      url: f.url,
      source: f.source,
      category: f.category,
      score: f.score,
      summary: f.summary,
    })),
    null,
    2
  );

  const prompt = `You are synthesizing a daily "What's New in AI Software Engineering" report.

**Period:** ${formatDate(periodStart)} to ${formatDate(periodEnd)} (${days} days)
**Total Findings:** ${findings.length} (${discoveries.length} discoveries, ${releases.length} releases, ${discussions.length} discussions, ${trends.length} trends)

**Available Findings (top 20 by score):**
\`\`\`json
${findingsJson}
\`\`\`

**Task:** Create an initial synthesis markdown report that:
1. Starts with a TL;DR section listing the top 5 most significant items
2. Groups findings into logical sections: "Releases & Updates", "New Tools & Discoveries", "Community Pulse"
3. For each item, include: title, URL, source, and brief context
4. Identifies cross-cutting themes and connections between items
5. Uses the exact format specified below

**Required Format:**
\`\`\`markdown
# What's New in AI Software Engineering

**Period:** YYYY-MM-DD to YYYY-MM-DD (X days)
**Generated:** [ISO timestamp]
**Findings:** X total

---

## TL;DR

1. **[Title](URL)** — Brief context
2. **[Title](URL)** — Brief context
...

## 📦 Releases & Updates

### Major Releases
- **[Title](URL)** — *Source* — Brief description

### Library Updates
- **[Title](URL)** — *Source* — Brief description

## 🔬 New Tools & Discoveries

### Trending Repositories
| Repository | Stars |
|------------|-------|
| [Repo](URL) | ⭐ X |

### Notable Discoveries
- **[Title](URL)** — *Source* — Brief description

## 💬 Community Pulse

### Reddit Discussions
| Post | Subreddit |
|------|-----------|
| [Title](URL) | r/subreddit |

### Social Media
- **[Title](URL)** — *Source* — Brief description

## 📈 Key Themes & Trends

[Identify 3-5 key themes emerging from the findings, with brief explanations]

---

**Sources:** Source1: X · Source2: Y · ...

*Generated by Holocron's What's New system*
\`\`\`

**Guidelines:**
- Be concise but informative
- Prioritize impactful items over popularity scores
- Highlight unexpected connections or insights
- Use the exact section headers specified
- Include all links in markdown [title](url) format

**Additional Task:** For each tool/library/framework mentioned that users might want to save:
1. Extract structured metadata: title, description, category, sourceUrl, sourceType, language, tags, useCases
2. Return these as a JSON array using this exact format after the markdown:

\`\`\`json
[
  {
    "id": "tool-1",
    "title": "Tool Name",
    "description": "Brief description",
    "category": "libraries",
    "sourceUrl": "https://...",
    "sourceType": "github",
    "language": "typescript",
    "tags": ["tag1", "tag2"],
    "useCases": ["use case 1", "use case 2"]
  }
]
\`\`\`

3. Include an "Add to Toolbelt" link in the markdown using:
   \`[📦 Add to Toolbelt](holocron://toolbelt/add?title={encoded_title}&description={encoded_description}&category={category}&sourceUrl={encoded_url}&sourceType={type}&language={lang}&tags={encoded_tags}&useCases={encoded_usecases})\`

Category options: libraries, cli, framework, service, database, tool
SourceType options: github, npm, pypi, website, cargo, go, other
All parameter values must be URL-encoded.`;

  try {
    const result = await generateText({
      model: zaiFlash(),
      prompt,
    });

    return result.text;
  } catch (error) {
    console.error("[Pass 1] LLM synthesis failed:", error);
    throw error;
  }
}

// ============================================================================
// Pass 2: Refinement
// ============================================================================

/**
 * Refine and improve the initial synthesis
 *
 * This pass:
 * - Improves writing quality and clarity
 * - Adds insights and connections
 * - Formats the final report
 * - Ensures consistency and completeness
 */
async function refineSynthesis(
  initialSynthesis: string,
  findings: Finding[],
  days: number,
  periodStart: Date,
  periodEnd: Date
): Promise<string> {
  const formatDate = (d: Date) => d.toISOString().split("T")[0];

  // Calculate source breakdown
  const sourceCounts = findings.reduce(
    (acc, f) => {
      acc[f.source] = (acc[f.source] || 0) + 1;
      return acc;
    },
    {} as Record<string, number>
  );
  const sourceBreakdown = Object.entries(sourceCounts)
    .sort((a, b) => b[1] - a[1])
    .map(([source, count]) => `${source}: ${count}`)
    .join(" · ");

  const prompt = `You are refining a daily "What's New in AI Software Engineering" report.

**Period:** ${formatDate(periodStart)} to ${formatDate(periodEnd)} (${days} days)
**Total Findings:** ${findings.length}

**Initial Synthesis:**
\`\`\`markdown
${initialSynthesis}
\`\`\`

**Task:** Refine the synthesis to:
1. Improve clarity, flow, and readability
2. Strengthen connections between related items
3. Add brief insightful commentary on key trends
4. Ensure all sections are well-organized and complete
5. Fix any formatting issues
6. Update the sources line to: **Sources:** ${sourceBreakdown}

**Guidelines:**
- Keep the same structure and section headers
- Maintain factual accuracy (don't invent details)
- Enhance writing quality with better transitions
- Add 1-2 sentences of insight for major themes
- Preserve all links and metadata
- Preserve any "Add to Toolbelt" links in the format: [📦 Add to Toolbelt](holocron://toolbelt/add?...)
- End with the exact footer: "*Generated by Holocron's What's New system*"

**Return the complete refined markdown report.**`;

  try {
    const result = await generateText({
      model: zaiPro(),
      prompt,
    });

    return result.text;
  } catch (error) {
    console.error("[Pass 2] LLM refinement failed:", error);
    throw error;
  }
}

// ============================================================================
// Static Fallback
// ============================================================================

/**
 * Generate a static fallback report when LLM is unavailable
 *
 * This ensures a report is always generated, even when:
 * - LLM API is down
 * - Rate limits are hit
 * - Network issues occur
 * - Timeout happens
 */
function generateStaticFallback(
  findings: Finding[],
  days: number,
  periodStart: Date,
  periodEnd: Date
): string {
  const formatDate = (d: Date) => d.toISOString().split("T")[0];

  const { discoveries, releases, trends, discussions } = {
    discoveries: findings.filter((f) => f.category === "discovery"),
    releases: findings.filter((f) => f.category === "release"),
    trends: findings.filter((f) => f.category === "trend"),
    discussions: findings.filter((f) => f.category === "discussion"),
  };

  // Build source breakdown
  const sourceCounts = findings.reduce(
    (acc, f) => {
      acc[f.source] = (acc[f.source] || 0) + 1;
      return acc;
    },
    {} as Record<string, number>
  );
  const sourceBreakdown = Object.entries(sourceCounts)
    .sort((a, b) => b[1] - a[1])
    .map(([source, count]) => `${source}: ${count}`)
    .join(" · ");

  // Format score
  const formatScore = (item: Finding): string => {
    if (!item.score) return "";
    if (item.source === "GitHub") return ` ⭐ ${item.score}`;
    return ` (${item.score} pts)`;
  };

  // Top by score
  const topByScore = (items: Finding[], n: number): Finding[] => {
    return [...items].sort((a, b) => (b.score ?? 0) - (a.score ?? 0)).slice(0, n);
  };

  let markdown = `# What's New in AI Software Engineering

**Period:** ${formatDate(periodStart)} to ${formatDate(periodEnd)} (${days} days)
**Generated:** ${new Date().toISOString()}
**Findings:** ${findings.length} total (${discoveries.length} discoveries, ${releases.length} releases, ${trends.length} trends, ${discussions.length} discussions)

---

`;

  // TL;DR
  const top5 = topByScore(findings, 5);
  if (top5.length > 0) {
    markdown += `## TL;DR\n\n`;
    for (let i = 0; i < top5.length; i++) {
      const item = top5[i];
      markdown += `${i + 1}. **[${item.title}](${item.url})**${formatScore(item)}\n`;
    }
    markdown += "\n---\n\n";
  }

  // Releases
  if (releases.length > 0) {
    markdown += `## 📦 Releases & Updates\n\n`;
    markdown += `| Release | Source | Score |\n`;
    markdown += `|---------|--------|-------|\n`;
    for (const item of releases.slice(0, 10)) {
      const score = item.score ? `${item.score}` : "—";
      markdown += `| [${item.title}](${item.url}) | ${item.source} | ${score} |\n`;
    }
    markdown += "\n";
  }

  // Discoveries
  if (discoveries.length > 0) {
    const githubFinds = discoveries.filter((f) => f.source === "GitHub");
    const otherFinds = discoveries.filter((f) => f.source !== "GitHub");

    markdown += `## 🔬 New Tools & Discoveries\n\n`;

    if (otherFinds.length > 0) {
      for (const item of otherFinds.slice(0, 10)) {
        markdown += `- **[${item.title}](${item.url})** — *${item.source}*${formatScore(item)}\n`;
        if (item.summary) {
          markdown += `  ${item.summary}\n`;
        }
      }
      markdown += "\n";
    }

    if (githubFinds.length > 0) {
      markdown += `### Trending Repos\n\n`;
      markdown += `| Repository | Stars |\n`;
      markdown += `|------------|-------|\n`;
      for (const item of topByScore(githubFinds, 10)) {
        markdown += `| [${item.title}](${item.url}) | ${item.score ? `⭐ ${item.score}` : "—"} |\n`;
      }
      markdown += "\n";
    }
  }

  // Discussions
  if (discussions.length > 0) {
    const redditPosts = discussions.filter((f) => f.source.startsWith("r/"));
    const lobsterPosts = discussions.filter((f) => f.source === "Lobsters");
    const otherDiscussions = discussions.filter(
      (f) => !f.source.startsWith("r/") && f.source !== "Lobsters"
    );

    markdown += `## 💬 Community Pulse\n\n`;

    if (redditPosts.length > 0) {
      markdown += `### Reddit\n\n`;
      markdown += `| Post | Subreddit |\n`;
      markdown += `|------|-----------|\n`;
      for (const item of redditPosts.slice(0, 10)) {
        markdown += `| [${item.title}](${item.url}) | ${item.source} |\n`;
      }
      markdown += "\n";
    }

    if (lobsterPosts.length > 0) {
      markdown += `### Lobsters\n\n`;
      for (const item of lobsterPosts.slice(0, 5)) {
        markdown += `- [${item.title}](${item.url})\n`;
      }
      markdown += "\n";
    }

    if (otherDiscussions.length > 0) {
      for (const item of otherDiscussions.slice(0, 5)) {
        markdown += `- [${item.title}](${item.url}) — *${item.source}*\n`;
      }
      markdown += "\n";
    }
  }

  // Trends
  if (trends.length > 0) {
    markdown += `## 📈 Trends\n\n`;
    for (const item of trends.slice(0, 10)) {
      markdown += `- **[${item.title}](${item.url})** — *${item.source}*\n`;
    }
    markdown += "\n";
  }

  // Footer
  markdown += `---\n\n`;
  markdown += `**Sources:** ${sourceBreakdown}\n\n`;
  markdown += `*Generated by Holocron's What's New system (static fallback)*\n`;

  return markdown;
}

// ============================================================================
// Main Synthesis Function
// ============================================================================

/**
 * Generate a synthesized report using two-pass LLM approach with static fallback
 *
 * @param findings - Array of findings to synthesize
 * @param days - Number of days covered by the report
 * @param periodStart - Start date of the period
 * @param periodEnd - End date of the period
 * @returns Synthesis result with markdown and method used
 */
export async function synthesizeReport(
  findings: Finding[],
  days: number,
  periodStart: Date,
  periodEnd: Date
): Promise<SynthesisResult> {
  console.log(
    `[synthesizeReport] Starting two-pass LLM synthesis (${findings.length} findings)`
  );

  // Validate inputs
  if (findings.length === 0) {
    console.log("[synthesizeReport] No findings, using minimal report");
    return {
      markdown: `# What's New in AI Software Engineering\n\nNo findings for this period.\n\n*Generated by Holocron's What's New system*`,
      method: "static-fallback",
    };
  }

  // Attempt two-pass LLM synthesis
  try {
    console.log("[synthesizeReport] Pass 1: Initial synthesis...");
    const pass1Start = Date.now();
    const initialSynthesis = await generateInitialSynthesis(
      findings,
      days,
      periodStart,
      periodEnd
    );
    const pass1Duration = Date.now() - pass1Start;
    console.log(`[synthesizeReport] Pass 1 complete (${pass1Duration}ms)`);

    // Parse tool suggestions from Pass 1 output
    let toolSuggestions: ToolSuggestion[] | undefined;
    const jsonMatch = initialSynthesis.match(/```json\n([\s\S]*?)\n```/);
    if (jsonMatch) {
      try {
        const parsed = JSON.parse(jsonMatch[1]);
        if (Array.isArray(parsed)) {
          toolSuggestions = parsed;
          console.log(`[synthesizeReport] Found ${toolSuggestions.length} tool suggestions`);
        }
      } catch (e) {
        console.log("[synthesizeReport] Failed to parse tool suggestions JSON:", e);
      }
    }

    console.log("[synthesizeReport] Pass 2: Refinement...");
    const pass2Start = Date.now();
    const refinedSynthesis = await refineSynthesis(
      initialSynthesis,
      findings,
      days,
      periodStart,
      periodEnd
    );
    const pass2Duration = Date.now() - pass2Start;
    console.log(`[synthesizeReport] Pass 2 complete (${pass2Duration}ms)`);

    console.log(
      `[synthesizeReport] Two-pass LLM synthesis successful (total: ${pass1Duration + pass2Duration}ms)`
    );

    return {
      markdown: refinedSynthesis,
      method: "llm-two-pass",
      pass1Content: initialSynthesis,
      toolSuggestions,
    };
  } catch (error) {
    console.error("[synthesizeReport] LLM synthesis failed, using static fallback:", error);
    const fallbackStart = Date.now();
    const fallbackReport = generateStaticFallback(
      findings,
      days,
      periodStart,
      periodEnd
    );
    const fallbackDuration = Date.now() - fallbackStart;
    console.log(`[synthesizeReport] Static fallback generated (${fallbackDuration}ms)`);

    return {
      markdown: fallbackReport,
      method: "static-fallback",
      error: error instanceof Error ? error.message : String(error),
    };
  }
}
