/**
 * Real pgBackRest healthy-chain seeder for Sprint 28 / REDHAT-FIX-C1.
 *
 * Seeds a test-scoped R2/repo prefix by running the real `pgbackrest` binary:
 *   stanza-create → INSERT pitr_test → full backup + dual WAL archive-push.
 *
 * NEVER uploads synthetic text manifests or HEALTHY-WAL-PLACEHOLDER.
 * Production archive_command is restored even on failure (finally).
 */
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { BackupConfig } from '../../../src/backup/config.ts';
import { endpointHost } from '../../../src/backup/config.ts';
import { listRepoPrefix } from '../../../src/backup/r2-provision.ts';

export type RealPgbackrestSeedResult = {
  ok: true;
  prefix: string;
  stanza: string;
  configPath: string;
  workDir: string;
  backupLabel: string;
  /** ISO-8601 UTC timestamp suitable for --pitr (within the backup WAL window). */
  pitrTimestamp: string;
  pitrTestRows: number;
  objectCount: number;
  seedLabel: string;
  seedBatch: string;
  infoJson: string;
};

export type RealPgbackrestSeedFailure = {
  ok: false;
  prefix: string;
  stanza: string;
  error: string;
  steps: Array<{ step: string; status: number | null; output: string }>;
};

export type RealPgbackrestSeedOutcome = RealPgbackrestSeedResult | RealPgbackrestSeedFailure;

function run(
  cmd: string,
  args: string[],
  options: { env?: NodeJS.ProcessEnv; timeoutMs?: number; cwd?: string } = {}
): { status: number | null; stdout: string; stderr: string } {
  const res = spawnSync(cmd, args, {
    encoding: 'utf8',
    env: options.env ?? process.env,
    timeout: options.timeoutMs ?? 120_000,
    cwd: options.cwd,
  });
  return {
    status: res.status,
    stdout: res.stdout ?? '',
    stderr: res.stderr ?? '',
  };
}

function psqlOnUrl(
  databaseUrl: string,
  sql: string,
  opts: { onErrorStop?: boolean } = {}
): { status: number | null; stdout: string; stderr: string } {
  const args = [databaseUrl];
  if (opts.onErrorStop !== false) {
    args.push('-v', 'ON_ERROR_STOP=1');
  }
  args.push('-tAc', sql);
  return run('psql', args, { timeoutMs: 30_000 });
}

function parseLatestBackupLabel(infoJson: string): string | null {
  try {
    const data = JSON.parse(infoJson) as Array<{
      backup?: Array<{ label?: string }>;
    }>;
    if (!Array.isArray(data) || data.length === 0) return null;
    const backups = data[0]?.backup ?? [];
    if (!Array.isArray(backups) || backups.length === 0) return null;
    const last = backups[backups.length - 1];
    return last?.label && last.label.length >= 8 ? last.label : null;
  } catch {
    const m = infoJson.match(/\b(\d{8}-\d{6}[FDI](?:_\d{8}-\d{6}[FDI])*)\b/);
    return m?.[1] ?? null;
  }
}

function parseBackupStopIso(infoJson: string, label: string): string | null {
  try {
    const data = JSON.parse(infoJson) as Array<{
      backup?: Array<{
        label?: string;
        timestamp?: { stop?: string | number; start?: string | number };
      }>;
    }>;
    const backups = data[0]?.backup ?? [];
    const hit = backups.find((b) => b.label === label) ?? backups[backups.length - 1];
    const stop = hit?.timestamp?.stop;
    if (typeof stop === 'number' && Number.isFinite(stop)) {
      // pgBackRest JSON often uses epoch seconds
      const ms = stop > 1e12 ? stop : stop * 1000;
      return new Date(ms).toISOString().replace(/\.\d{3}Z$/, 'Z');
    }
    if (typeof stop === 'string' && stop.length >= 10) {
      const d = new Date(stop);
      if (!Number.isNaN(d.getTime())) {
        return d.toISOString().replace(/\.\d{3}Z$/, 'Z');
      }
    }
  } catch {
    /* fall through */
  }
  return null;
}

function pgbackrestEnv(cfg: BackupConfig, env: NodeJS.ProcessEnv): NodeJS.ProcessEnv {
  const out: NodeJS.ProcessEnv = {
    ...env,
    PGBACKREST_REPO1_S3_KEY: cfg.accessKeyId,
    PGBACKREST_REPO1_S3_KEY_SECRET: cfg.secretAccessKey,
    PATH: `/opt/homebrew/bin:/usr/bin:/bin:${env.PATH ?? ''}`,
  };
  if (cfg.sessionToken) {
    out.PGBACKREST_REPO1_S3_TOKEN = cfg.sessionToken;
  } else {
    delete out.PGBACKREST_REPO1_S3_TOKEN;
  }
  return out;
}

function renderTestConf(options: {
  stanza: string;
  pg1Path: string;
  bucketName: string;
  endpointHost: string;
  repoPath: string;
  cipherPass: string;
  accessKeyId: string;
  secretAccessKey: string;
  sessionToken: string | null;
}): string {
  const keyLines = [
    `repo1-s3-key=${options.accessKeyId}`,
    `repo1-s3-key-secret=${options.secretAccessKey}`,
  ];
  if (options.sessionToken) {
    keyLines.push(`repo1-s3-token=${options.sessionToken}`);
  }
  return `# Generated by REDHAT-FIX-C1 test seeder — never commit.
[global]
repo1-type=s3
repo1-s3-bucket=${options.bucketName}
repo1-s3-endpoint=${options.endpointHost}
repo1-s3-region=auto
repo1-s3-uri-style=path
repo1-path=/${options.repoPath.replace(/^\//, '')}
${keyLines.join('\n')}
repo1-cipher-type=aes-256-cbc
repo1-cipher-pass=${options.cipherPass}
repo1-retention-full=2
repo1-bundle=y
repo1-block=y
process-max=2
start-fast=y
log-level-console=info
log-level-file=off

[${options.stanza}]
pg1-path=${options.pg1Path}
pg1-port=5432
`;
}

/**
 * Seed a REAL pgBackRest full backup + WAL into `options.prefix` on R2.
 *
 * Uses a unique stanza to avoid lock contention with production `main` restore/backup.
 * Temporarily dual-archives WAL (prod + test) so backup can complete against the
 * test-scoped repo path, then restores the original archive_command.
 */
export function seedRealPgbackrestHealthyChain(options: {
  cfg: BackupConfig;
  prefix: string;
  /** Source DB URL for pitr_test insert (cluster-wide backup covers all DBs). */
  databaseUrl: string;
  /** Production pgBackRest conf used by the live archive_command (for dual-push). */
  productionConfigPath: string;
  runId: string;
  /** Optional stanza name (default d05seed-<short>). */
  stanza?: string;
  pg1Path?: string;
}): RealPgbackrestSeedOutcome {
  const steps: Array<{ step: string; status: number | null; output: string }> = [];
  const stanza =
    options.stanza ??
    `d05s${
      options.runId
        .replace(/[^a-z0-9]/gi, '')
        .slice(-10)
        .toLowerCase() || 'eed'
    }`;
  const pg1Path = options.pg1Path ?? options.cfg.pg1Path;
  const prodConf = options.productionConfigPath;
  const workDir = mkdtempSync(join(tmpdir(), 'd05-01-pgbr-seed-'));
  const logPath = join(workDir, 'log');
  mkdirSync(logPath, { recursive: true });
  const configPath = join(workDir, 'pgbackrest.conf');
  const seedLabel = `d05-01-healthy-seed-${options.runId}`;
  const seedBatch = 'd05-01-healthy';

  const confBody = renderTestConf({
    stanza,
    pg1Path,
    bucketName: options.cfg.bucketName,
    endpointHost: endpointHost(options.cfg.endpoint),
    repoPath: options.prefix,
    cipherPass: options.cfg.repoCipherPass,
    accessKeyId: options.cfg.accessKeyId,
    secretAccessKey: options.cfg.secretAccessKey,
    sessionToken: options.cfg.sessionToken,
  });
  writeFileSync(configPath, confBody, { mode: 0o600 });

  const env = pgbackrestEnv(options.cfg, process.env);
  const dbUrl = options.databaseUrl;

  // Capture original archive_command so we always restore it.
  const showArch = psqlOnUrl(dbUrl, 'SHOW archive_command');
  steps.push({
    step: 'show_archive_command',
    status: showArch.status,
    output: (showArch.stdout || showArch.stderr).slice(0, 400),
  });
  if (showArch.status !== 0) {
    rmSync(workDir, { recursive: true, force: true });
    return {
      ok: false,
      prefix: options.prefix,
      stanza,
      error: `database unreachable while reading archive_command: ${showArch.stderr || showArch.stdout}`,
      steps,
    };
  }
  const originalArchive = showArch.stdout.trim();

  const dualCmd =
    `/bin/bash -c '/opt/homebrew/bin/pgbackrest --config=${prodConf} --stanza=main archive-push "$1" && ` +
    `/opt/homebrew/bin/pgbackrest --config=${configPath} --stanza=${stanza} --log-path=${logPath} archive-push "$1"' -- %p`;

  const restoreArchiveCommand = () => {
    // ALTER SYSTEM cannot share a multi-statement transaction with SELECT — separate calls.
    const a = run(
      'psql',
      [
        dbUrl,
        '-v',
        'ON_ERROR_STOP=1',
        '-c',
        `ALTER SYSTEM SET archive_command TO '${originalArchive.replace(/'/g, "''")}'`,
      ],
      { timeoutMs: 15_000 }
    );
    const b = run('psql', [dbUrl, '-v', 'ON_ERROR_STOP=1', '-c', 'SELECT pg_reload_conf();'], {
      timeoutMs: 15_000,
    });
    steps.push({
      step: 'restore_archive_command',
      status: a.status === 0 && b.status === 0 ? 0 : (a.status ?? b.status),
      output: `${a.stdout}${a.stderr}${b.stdout}${b.stderr}`.slice(0, 400),
    });
  };

  try {
    // Dual-archive for the seed window (must contain literal "pgbackrest").
    const setArch = run(
      'psql',
      [
        dbUrl,
        '-v',
        'ON_ERROR_STOP=1',
        '-c',
        `ALTER SYSTEM SET archive_command TO '${dualCmd.replace(/'/g, "''")}'`,
      ],
      { timeoutMs: 15_000 }
    );
    steps.push({
      step: 'set_dual_archive_command',
      status: setArch.status,
      output: (setArch.stdout || setArch.stderr).slice(0, 400),
    });
    if (setArch.status !== 0) {
      return {
        ok: false,
        prefix: options.prefix,
        stanza,
        error: `failed to set dual archive_command: ${setArch.stderr || setArch.stdout}`,
        steps,
      };
    }
    const reload = run('psql', [dbUrl, '-v', 'ON_ERROR_STOP=1', '-c', 'SELECT pg_reload_conf();'], {
      timeoutMs: 15_000,
    });
    steps.push({
      step: 'reload_conf',
      status: reload.status,
      output: (reload.stdout || reload.stderr).slice(0, 200),
    });

    // Ensure pitr_test exists with the live schema (label + batch) and seed a row.
    // Prefer INSERT against existing table (Sprint 28 schema); create only if missing.
    const ensureTable = psqlOnUrl(dbUrl, `SELECT to_regclass('public.pitr_test') IS NOT NULL`);
    steps.push({
      step: 'check_pitr_test_table',
      status: ensureTable.status,
      output: ensureTable.stdout || ensureTable.stderr,
    });
    if (ensureTable.status !== 0) {
      return {
        ok: false,
        prefix: options.prefix,
        stanza,
        error: `database unreachable while probing pitr_test: ${ensureTable.stderr || ensureTable.stdout}`,
        steps,
      };
    }
    if (ensureTable.stdout.trim() !== 't') {
      const create = psqlOnUrl(
        dbUrl,
        `CREATE TABLE pitr_test (
          id bigserial PRIMARY KEY,
          label text NOT NULL,
          batch text NOT NULL,
          created_at timestamptz NOT NULL DEFAULT now()
        )`
      );
      steps.push({
        step: 'create_pitr_test',
        status: create.status,
        output: (create.stdout || create.stderr).slice(0, 400),
      });
      if (create.status !== 0) {
        return {
          ok: false,
          prefix: options.prefix,
          stanza,
          error: `failed to create pitr_test: ${create.stderr || create.stdout}`,
          steps,
        };
      }
    }

    const insert = psqlOnUrl(
      dbUrl,
      `INSERT INTO pitr_test (label, batch) VALUES ('${seedLabel.replace(/'/g, "''")}', '${seedBatch}')`
    );
    steps.push({
      step: 'insert_pitr_test',
      status: insert.status,
      output: (insert.stdout || insert.stderr).slice(0, 400),
    });
    if (insert.status !== 0) {
      return {
        ok: false,
        prefix: options.prefix,
        stanza,
        error: `failed to insert pitr_test seed: ${insert.stderr || insert.stdout}`,
        steps,
      };
    }

    // Separate queries — multi-statement -tAc output is easy to mis-parse.
    const countRes = psqlOnUrl(
      dbUrl,
      `SELECT COUNT(*)::text FROM pitr_test WHERE batch = '${seedBatch}'`
    );
    steps.push({
      step: 'count_pitr_test',
      status: countRes.status,
      output: (countRes.stdout || countRes.stderr).slice(0, 200),
    });
    if (countRes.status !== 0 || !/^\d+$/.test(countRes.stdout.trim())) {
      return {
        ok: false,
        prefix: options.prefix,
        stanza,
        error: `failed to count pitr_test seed rows: ${countRes.stderr || countRes.stdout}`,
        steps,
      };
    }
    const pitrTestRows = Number(countRes.stdout.trim());

    const tsRes = psqlOnUrl(
      dbUrl,
      `SELECT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')`
    );
    const insertTs =
      tsRes.status === 0 && tsRes.stdout.trim().length > 0
        ? tsRes.stdout.trim()
        : new Date().toISOString().replace(/\.\d{3}Z$/, 'Z');

    // stanza-create on the test-scoped prefix
    const createStanza = run(
      'pgbackrest',
      [`--config=${configPath}`, `--stanza=${stanza}`, `--log-path=${logPath}`, 'stanza-create'],
      { env, timeoutMs: 180_000 }
    );
    steps.push({
      step: 'stanza-create',
      status: createStanza.status,
      output: `${createStanza.stdout}\n${createStanza.stderr}`.slice(0, 800),
    });
    if (createStanza.status !== 0) {
      return {
        ok: false,
        prefix: options.prefix,
        stanza,
        error: `pgbackrest stanza-create exit ${createStanza.status}: ${createStanza.stderr || createStanza.stdout}`,
        steps,
      };
    }

    // Force a WAL switch so dual archive-push covers the insert before backup.
    const walSwitch = psqlOnUrl(dbUrl, `SELECT pg_switch_wal(); SELECT pg_sleep(2);`);
    steps.push({
      step: 'pg_switch_wal',
      status: walSwitch.status,
      output: (walSwitch.stdout || walSwitch.stderr).slice(0, 200),
    });

    // Real full backup into the test-scoped R2 prefix.
    const backup = run(
      'pgbackrest',
      [
        `--config=${configPath}`,
        `--stanza=${stanza}`,
        '--type=full',
        '--no-archive-mode-check',
        `--log-path=${logPath}`,
        'backup',
      ],
      { env, timeoutMs: 600_000 }
    );
    steps.push({
      step: 'pgbackrest_backup',
      status: backup.status,
      output: `${backup.stdout}\n${backup.stderr}`.slice(0, 1200),
    });
    if (backup.status !== 0) {
      return {
        ok: false,
        prefix: options.prefix,
        stanza,
        error: `pgbackrest backup exit ${backup.status}: ${(backup.stderr || backup.stdout).slice(0, 600)}`,
        steps,
      };
    }

    // Another WAL switch after backup to extend the continuous archive window.
    const walSwitch2 = psqlOnUrl(dbUrl, `SELECT pg_switch_wal(); SELECT pg_sleep(2);`);
    steps.push({
      step: 'pg_switch_wal_after_backup',
      status: walSwitch2.status,
      output: (walSwitch2.stdout || walSwitch2.stderr).slice(0, 200),
    });

    const info = run(
      'pgbackrest',
      [
        `--config=${configPath}`,
        `--stanza=${stanza}`,
        `--log-path=${logPath}`,
        'info',
        '--output=json',
      ],
      { env, timeoutMs: 120_000 }
    );
    steps.push({
      step: 'pgbackrest_info',
      status: info.status,
      output: (info.stdout || info.stderr).slice(0, 800),
    });
    if (info.status !== 0) {
      return {
        ok: false,
        prefix: options.prefix,
        stanza,
        error: `pgbackrest info exit ${info.status}: ${info.stderr || info.stdout}`,
        steps,
      };
    }

    const backupLabel = parseLatestBackupLabel(info.stdout);
    if (!backupLabel || backupLabel.length < 8) {
      return {
        ok: false,
        prefix: options.prefix,
        stanza,
        error: `pgbackrest info did not report a real backup label (>=8 chars); got ${backupLabel ?? 'null'}`,
        steps,
      };
    }

    const listed = listRepoPrefix({
      accessKeyId: options.cfg.accessKeyId,
      secretAccessKey: options.cfg.secretAccessKey,
      sessionToken: options.cfg.sessionToken,
      endpoint: options.cfg.endpoint,
      bucketName: options.cfg.bucketName,
      prefix: options.prefix,
    });
    steps.push({
      step: 'r2_list_prefix',
      status: listed.count >= 1 ? 0 : 1,
      output: `count=${listed.count}`,
    });
    if (listed.count < 1) {
      return {
        ok: false,
        prefix: options.prefix,
        stanza,
        error: `R2 object_count under ${options.prefix} is 0 after real backup`,
        steps,
      };
    }

    // Prefer backup stop time (guaranteed in WAL window); fall back to insert timestamp.
    const pitrTimestamp = parseBackupStopIso(info.stdout, backupLabel) ?? insertTs;

    return {
      ok: true,
      prefix: options.prefix,
      stanza,
      configPath,
      workDir,
      backupLabel,
      pitrTimestamp,
      pitrTestRows: Number.isFinite(pitrTestRows) ? pitrTestRows : 0,
      objectCount: listed.count,
      seedLabel,
      seedBatch,
      infoJson: info.stdout,
    };
  } finally {
    try {
      restoreArchiveCommand();
    } catch (e) {
      steps.push({
        step: 'restore_archive_command_throw',
        status: 1,
        output: e instanceof Error ? e.message : String(e),
      });
    }
  }
}

/** Best-effort cleanup of seeder workdir (conf may contain cipher pass). */
export function cleanupPgbackrestSeedWorkDir(workDir: string | undefined): void {
  if (!workDir || !existsSync(workDir)) return;
  try {
    rmSync(workDir, { recursive: true, force: true });
  } catch {
    /* best-effort */
  }
}
