/**
 * Centralized icon barrel — ALL icon usage in the app should import from here.
 *
 * This file applies NativeWind `cssInterop` to every Lucide icon so that
 * className-based theming (e.g. `className="text-foreground"`) works correctly
 * on React Native. Without this wrapper, `color` from className is ignored
 * because Lucide icons expect `color` as a prop, not a style property.
 *
 * If you need a new icon, add the import here and it will automatically
 * get cssInterop applied via the `icons` array + loop below.
 */
import { cssInterop } from 'nativewind'

import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BarChart3,
  Bell,
  BookmarkPlus,
  BookOpen,
  Bot,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Code,
  Database,
  DollarSign,
  EllipsisVertical,
  ExternalLink,
  FileQuestion,
  FileText,
  Filter,
  Flame,
  Folder,
  FolderOpen,
  Gauge,
  GitFork,
  Globe,
  Hash,
  Home,
  Inbox,
  Lightbulb,
  Link,
  Loader2,
  Lock,
  Megaphone,
  Menu,
  MessageSquare,
  Mic,
  MicOff,
  Newspaper,
  Package,
  Pause,
  Pencil,
  PenSquare,
  Play,
  Plus,
  RefreshCw,
  Rss,
  Search,
  Send,
  Settings,
  Share2,
  ShoppingCart,
  SkipBack,
  SkipForward,
  Sparkles,
  SquarePen,
  Star,
  Tag,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  User,
  WandSparkles,
  Wrench,
  X,
  XCircle,
  Zap,
} from 'lucide-react-native'

// Re-export type-only imports consumers need
export type { LucideIcon, LucideProps } from 'lucide-react-native'

// ── Apply cssInterop to every icon ──────────────────────────────────────
// Maps: className  → style  (NativeWind)
//       style.color → color prop  (Lucide)
//       style.height/width → size prop  (Lucide)
const icons = [
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BarChart3,
  Bell,
  BookmarkPlus,
  BookOpen,
  Bot,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Code,
  Database,
  DollarSign,
  EllipsisVertical,
  ExternalLink,
  FileQuestion,
  FileText,
  Filter,
  Flame,
  Folder,
  FolderOpen,
  Gauge,
  GitFork,
  Globe,
  Hash,
  Home,
  Inbox,
  Lightbulb,
  Link,
  Loader2,
  Lock,
  Megaphone,
  Menu,
  MessageSquare,
  Mic,
  MicOff,
  Newspaper,
  Package,
  Pause,
  Pencil,
  PenSquare,
  Play,
  Plus,
  RefreshCw,
  Rss,
  Search,
  Send,
  Settings,
  Share2,
  ShoppingCart,
  SkipBack,
  SkipForward,
  Sparkles,
  SquarePen,
  Star,
  Tag,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  User,
  WandSparkles,
  Wrench,
  X,
  XCircle,
  Zap,
] as const

for (const icon of icons) {
  cssInterop(icon, {
    className: {
      target: 'style',
      nativeStyleToProp: {
        color: 'color',
        height: 'size',
        width: 'size',
      },
    },
  })
}

// ── Re-export every icon (same names, now themed) ───────────────────────
export {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BarChart3,
  Bell,
  BookmarkPlus,
  BookOpen,
  Bot,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Code,
  Database,
  DollarSign,
  EllipsisVertical,
  ExternalLink,
  FileQuestion,
  FileText,
  Filter,
  Flame,
  Folder,
  FolderOpen,
  Gauge,
  GitFork,
  Globe,
  Hash,
  Home,
  Inbox,
  Lightbulb,
  Link,
  Loader2,
  Lock,
  Megaphone,
  Menu,
  MessageSquare,
  Mic,
  MicOff,
  Newspaper,
  Package,
  Pause,
  Pencil,
  PenSquare,
  Play,
  Plus,
  RefreshCw,
  Rss,
  Search,
  Send,
  Settings,
  Share2,
  ShoppingCart,
  SkipBack,
  SkipForward,
  Sparkles,
  SquarePen,
  Star,
  Tag,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  User,
  WandSparkles,
  Wrench,
  X,
  XCircle,
  Zap,
}
