#!/usr/bin/env bash
# GATE-FIX-S28R3-QA2 / C2 — Regenerate HUMAN-GATE.md from gate-plan.json literal_cmd.
#
# Authoritative executable commands are ONLY gate-plan.json steps.
# This script embeds each step's literal_cmd and its sha256 for oracle lock.
#
# Usage:
#   ./scripts/render-human-gate-from-plan.sh
#   ./scripts/render-human-gate-from-plan.sh --plan PATH --out PATH
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PLAN="${ROOT}/.spec/prds/mk6-migration/tasks/sprint-28-point-in-time-restore-and-fresh-hardware-fire-drill/gate-plan.json"
OUT="${ROOT}/.spec/prds/mk6-migration/tasks/sprint-28-point-in-time-restore-and-fresh-hardware-fire-drill/HUMAN-GATE.md"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --plan) PLAN="${2:-}"; shift 2 ;;
    --out) OUT="${2:-}"; shift 2 ;;
    -h|--help)
      echo "Usage: render-human-gate-from-plan.sh [--plan gate-plan.json] [--out HUMAN-GATE.md]"
      exit 0
      ;;
    *)
      echo "error: unknown argument: $1" >&2
      exit 2
      ;;
  esac
done

if [[ ! -f "$PLAN" ]]; then
  echo "error: gate-plan missing: $PLAN" >&2
  exit 2
fi

python3 - "$PLAN" "$OUT" <<'PY'
import hashlib, json, sys
from pathlib import Path

plan_path, out_path = Path(sys.argv[1]), Path(sys.argv[2])
plan = json.loads(plan_path.read_text(encoding="utf-8"))
steps = plan.get("steps") or []

lines: list[str] = []
lines.append("# Sprint 28 — Human Testing Gate (executable)")
lines.append("")
lines.append("**Capability:** CAP-BAK-01 (PITR + fresh-hardware fire-drill)")
lines.append("**Dispatcher:** `bun services/platform/src/cli/holo.ts` (never a PATH `holo` stub)")
lines.append("**Machine plan (sole authoritative source of literal commands):** [`gate-plan.json`](./gate-plan.json)")
lines.append("")
lines.append("> **GATE-FIX-S28R3-QA2:** The **only** authoritative executable commands are the")
lines.append("> `literal_cmd` fields in `gate-plan.json`. This file is regenerated by")
lines.append("> `scripts/render-human-gate-from-plan.sh` and embeds each step command + sha256")
lines.append("> so operators and oracles cannot drift from the machine plan.")
lines.append("")
lines.append("## Preconditions")
lines.append("")
lines.append("```bash")
lines.append('export HOLO_SECRETS_PATH="${HOLO_SECRETS_PATH:-services/platform/config/secrets.yaml}"')
lines.append("# Live runs REQUIRE a nonempty allowlisted GATE_RUN_ID:")
lines.append("#   pattern: ^[A-Za-z0-9][A-Za-z0-9_-]{0,62}[A-Za-z0-9]$  (or single alnum)")
lines.append("#   length: 1–64; alphanumeric plus '-' / '_' only; no spaces or path chars")
lines.append('export GATE_RUN_ID="${GATE_RUN_ID:?set allowlisted GATE_RUN_ID for live runs}"')
lines.append('export PITR_TIMESTAMP="${PITR_TIMESTAMP:?set in-window ISO for positive fire-drill steps}"')
lines.append("```")
lines.append("")
lines.append("Residual until distinct live `R2_RESTORE_*` credentials exist: **`DEPENDENCY-S28-R2-RO`**.")
lines.append("")
lines.append("## Automated oracle suites (preferred pre-check)")
lines.append("")
lines.append("```bash")
lines.append("pnpm vitest run services/platform/tests/integration/sprint28-capability-inventory.test.ts")
lines.append("PLATFORM_IT=1 pnpm vitest run services/platform/tests/integration/sprint28-human-gate-oracles.test.ts")
lines.append("PLATFORM_IT=1 pnpm vitest run services/platform/tests/integration/sprint28-s28r3-qa2-gate-fix.test.ts")
lines.append("PLATFORM_IT=1 pnpm vitest run services/platform/tests/integration/sprint28-restore-fails-closed.test.ts")
lines.append("```")
lines.append("")
lines.append("## Six gate steps (from gate-plan.json `literal_cmd`)")
lines.append("")
lines.append("Each block below is the **exact** `literal_cmd` string from the plan (not a paraphrase).")
lines.append("Oracle: `sha256(documented_cmd) == sha256(gate-plan.steps[n].literal_cmd)`.")
lines.append("")

for step in steps:
    n = step.get("n")
    text = step.get("text") or ""
    cmd = step.get("literal_cmd") or ""
    digest = hashlib.sha256(cmd.encode("utf-8")).hexdigest()
    lines.append(f"### {n} — {text}")
    lines.append("")
    lines.append(f"`literal_cmd_sha256: {digest}`")
    lines.append("")
    lines.append("```bash")
    lines.append(cmd)
    lines.append("```")
    lines.append("")
    notes = (step.get("assertion") or {}).get("notes")
    if notes:
        lines.append(f"_Assertion notes:_ {notes}")
        lines.append("")

lines.append("## Evidence paths")
lines.append("")
lines.append("| Artifact | Path |")
lines.append("|----------|------|")
lines.append("| Capability inventory | `.tmp/REDHAT-FIX-H1/capability-inventory.json` |")
lines.append("| Human-gate oracle evidence | `.tmp/REDHAT-FIX-H2/**` |")
lines.append("| S28R3 volume-bound fire-drill | `.tmp/REDHAT-FIX-S28R3/**` |")
lines.append("| QA2 gate-fix evidence | `.tmp/GATE-FIX-S28R3-QA2/**` |")
lines.append("| Credential inventory (redacted) | `.tmp/GATE-FIX-S28R3-QA2/credential-inventory.json` |")
lines.append("")
lines.append("## Regenerating this file")
lines.append("")
lines.append("```bash")
lines.append("bash scripts/render-human-gate-from-plan.sh")
lines.append("```")
lines.append("")

out_path.write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {out_path} ({len(steps)} steps)")
PY
